### ISSUE TITLE
Client design

### ISSUE THREAD

**Issue by dmatuschek** [PantelisGeorgiadis/dcmjs-dimse#22]
While trying to implement a C-Store SCU, I noticed that you need to add requests before you initialize the association with the peer AE. This means in case you want to send a whole study, you need to load the whole study first, right?

Therefore what I mean is, the code for a C-Store SCU to send the whole study should look like this:
```TS
const client = new Client();
const path = `/path/to/dicom/study`;
const studyFiles = fs.readdirSync(path);

studyFiles.forEach((file) => {
    const dataset = Dataset.fromFile(`${path}/${file}`);

    // Do some image specific operations
    
    client.addRequest(new CStoreRequest(dataset));
});

client.on('networkError', (e) => {
    logger.error(`Network error: ${e} - [${path}]`, '[DICOM-SCU]');
});

client.send(ip, port, sendingAe, receivingAe);
```

If you are forced to do this before you send it, you are forced to load the whole study into the RAM. I think a better approach would be, to create a new association and allow sending the requests one after another, e.g.:

```TS
const client = new Client(ip, port, sendingAe, receivingAe);
const path = `/path/to/dicom/study`;
const studyImages = fs.readdirSync(path);

client.on('networkError', (e) => {
    logger.error(`Network error: ${e} - [${path}]`, '[DICOM-SCU]');
});

// ============ Method A =============
await client.connect(); 
for(const image of studyImages) {
    const dataset = Dataset.fromFile(`${path}/${image}`);

    // Do some image specific operations

    await client.sendRequest(new CStoreRequest(dataset));
}

client.close();

// ============ Method B =============

client.on('associationAccepted', async (network) => {
    for(const image of studyImages) {
        const dataset = Dataset.fromFile(`${path}/${image}`);
    
        // Do some image specific operations
    
        await network.sendRequest(new CStoreRequest(dataset));
    }
    client.close();
})
```

**Comment by PantelisGeorgiadis** [comment]
Hello @dmatuschek!
Thank you for your comment! You are absolutely right! C-STORE SCU is one of the places that could be heavily optimized (especially for large studies)! I’ve started dcmjs-dimse just to understand the internals of the DICOM networking protocol and, therefore, there are several places in the library that could undergo significant optimizations. It is in my plans to do some of them and the C-STORE SCU is one of them! Thank you for your proposal! I will definitely consider the methods you are proposing! 

One fast optimization would be to expose the dcmjs’s `untilTag` reading property in the `fromFile` function and read initially up to `(0002,0012) - Implementation Class UID`. Use the `(0002,0002) - Media Storage SOP Class UID` and `(0002,0010) - Transfer Syntax UID` tags to form the association presentation contexts and parse the complete file when it is ready to be sent. This way only one complete file will be loaded in memory at time plus the SOP class UID and transfer syntax pairs.

Thoughts?

**Comment by PantelisGeorgiadis** [comment]
Hello @dmatuschek!
I’ve pushed the above idea and it seems to be working really nice. The trick is to construct the `CStoreRequest` class, passing the file path, and not to load it yourself using `Dataset.fromFile`. If you do that, the class internally loads up to SOP instance UID tag (SOP class UID, SOP instance UID and transfer syntax are needed to form the proper command and association objects) and marks the command as “dataset needs full loading”, which is performed right before processing/sending the C-STORE request. In this way, the optimization is applied with zero code changes for the callers!

Unfortunately, I realized that your proposed methods wouldn’t work because, in the DICOM world, there’s no simple concept of just “connect” (your `await client.connect();`). Physical connection needs to be followed by an association request that contains objects called presentation contexts that are formed from the SOP class UIDs and transfer syntaxes of the datasets to be pushed (in the case of C-STORE SCU). SOP instance UIDs are also required so they can populate the commands affected SOP instance UID tags. Therefore, all datasets need to be pre-scanned to extract that information and form the proper association object. This can be avoided if the caller already knows the “type” and “syntax” of the datasets to be sent and, in that case, the library already provides support for creating custom association/presentation context objects.


Looking forward for your feedback!
