### ISSUE TITLE
Forcing ExplicitVRLittleEndian for sending of Private/Custom Tags

### ISSUE THREAD

**Issue by seanjb** [PantelisGeorgiadis/dcmjs-dimse#52]
Hi there,
We are trying to send an SR dataset with private tags using the client and cstore methods. Noticing a strange behaviour when including custom tags however that someone may be able to assist with. 

Based on this guide https://www.medicalconnections.co.uk/kb/DICOM-Private-Elements Private Tags will not work when using ImplicitVRLittleEndian.

We construct our Dataset using the following private tags using the datasetNameMap functionality and encountering an issue :
(7007,0010): Our private descriptor
(7007,1010): Some data1
(7007,1010): Some data2

If we construct the dataset using ImplicitVRLittleEndian, when written to a file the 7007,0010 values display fine, however the 7007,10xx values display as binary with a VR type unknown. When we send the data to a PACS (Orthanc) the values are blank. Expected based on the above link.

Interestingly if we construct the dataset using ExplicitVRLittleEndian , when written to a file all the values are correct. However when we send the data to a PACS (Orthanc) the values are still blank. 

On investigation, when the client warms up it proceeds to do an association request and offers both ImplicitVRLittleEndian and ExplicitVRLittleEndian set here https://github.com/PantelisGeorgiadis/dcmjs-dimse/blob/fbce1953bb3402054a8e1186bf4f30c8012016da/src/Client.js#L144-L147 

In our case the server we are contacting (Orthanc) prefers ImplicitVRLittleEndian but can receive both. However in the association response it just lists ImplicitVRLittleEndian. So the client sends our data as ImplicitVRLittleEndian causing the corruption issue.
![image](https://github.com/PantelisGeorgiadis/dcmjs-dimse/assets/6440630/df262b5e-a592-4ce5-aeef-58c5e6f0654c)

![image](https://github.com/PantelisGeorgiadis/dcmjs-dimse/assets/6440630/36b70cc0-6599-44f1-8498-2772caf938e4)

Is there a way to force the client to offer only ExplicitVRLittleEndian?

**Comment by PantelisGeorgiadis** [comment]
Hello @seanjb,
Thank you for your question! Actually, the Implicit VR Little Endian transfer syntax is the only mandatory DICOM transfer syntax! In your case, where the server decides to priorize `ImplicitVRLittleEndian`, then it is the server's decission, not yours. I'm pretty confident that Orthanc allows for a preferred transfer syntax to be set (if not per SOP class, definitely in general) and, in my opinion, this is the way you should go, rather than proposing non-valid presentation contexts.

One hack that I could think of, is to propose an extra presentation context for the `ComprehensiveSrStorage` with just the the `ExplicitVRLittleEndian` transfer syntax, "hoping" that the server will accept this one rather than the first one.
```js
client.addAdditionalPresentationContext(
  new PresentationContext(0, StorageClass.ComprehensiveSrStorage, TransferSyntax.ExplicitVRLittleEndian),
  true
);
```
However, I strongly suggest you to find a way to set the preferred transfer syntax in Orthanc.

**Comment by seanjb** [comment]
Thanks @PantelisGeorgiadis  extremely useful and insightful I was not aware it was a Mandatory syntax. So your advice makes complete sense, thank you.
