### ISSUE TITLE
Do you have any plans to support BigEndianExplicit transfer syntax?

### ISSUE THREAD

**Issue by suoc** [PantelisGeorgiadis/dcmjs-dimse#56]
Is there a plan  for this?

**Comment by suoc** [comment]
My mistake

**Comment by PantelisGeorgiadis** [comment]
Hello @suoc!
Thank you for your question! Although the Explicit VR Big Endian transfer syntax (1.2.840.10008.1.2.2) has been [officially retired since 2006](https://dicom.nema.org/medical/Dicom/current/output/chtml/part05/sect_A.3.html), `dcmjs` is supporting it and, therefore inherently, it is supported in `dcmjs-dimse`. It is not one of the syntaxes that are proposed by default, however, you can easily add it to your proposed contexts through the `addAdditionalPresentationContext` `Client` function.

**Comment by PantelisGeorgiadis** [comment]
Hey @suoc, do you have any sample code that I can use to test this?

**Comment by suoc** [comment]
I use your C-Store sample code for the testing. The client used the IQ-DICOMTEST testing tool.

**Comment by suoc** [comment]
[iQ-DICOMTEST 4.0.0.zip](https://github.com/PantelisGeorgiadis/dcmjs-dimse/files/14318367/iQ-DICOMTEST.4.0.0.zip)

**Comment by PantelisGeorgiadis** [comment]
Hello @suoc! Your observation was correct! Although `dcmjs` is able to handle `Explicit VR Big Endian` datasets, the `Dataset` class wasn't providing the information required to the library, so it can properly parse them. This is now fixed in version 0.1.25. Please test and let me know.

**Comment by suoc** [comment]
Excellent! The test was successful. Your test cases may need to be updated. The dcmjs v0.29.x contains several incompatible changes.

**Comment by PantelisGeorgiadis** [comment]
Thank you for verifying this @suoc! Yes, I'm aware that there are breaking changes introduced in dcmjs after version 0.29.10 and that's the reason for sticking to this, for now.

**Comment by suoc** [comment]
In the package.json file, the dcmjs dependency should be specified as 0.29.10 rather than ^0.29.10. Furthermore, the package-lock.json file needs to be regenerated.

**Comment by PantelisGeorgiadis** [comment]
Once again, thank you @suoc! In the latest release (0.1.26), the library is targeting specifically dcmjs version 0.29.10. Until the tests are updated to work with the latest dcmjs version, we can stick to this one.
