### ISSUE TITLE
Enforce a maximum length when setting the implementation version

### ISSUE THREAD

**Issue by will2hew** [PantelisGeorgiadis/dcmjs-dimse#61]
In the DICOM spec, the implementation version (as set by the `setImplementationVersion`) should be a maximum of 16 characters. 

We observed in the wild silent failures - association requested, association accepted, and then abandoning the connection - no discernible error on either the DICOM SCU or on our SCP. 

I would recommend we enforce that in dcmjs-dimse to prevent such a tricky error causing someone else pain in the future!

**Comment by PantelisGeorgiadis** [comment]
Hello Will!
Totally agree! It would be great if `dcmjs` had a tag value validation layer, based on their VR, but since it doesn't have that, we could apply some logic to the most critical parts of the communication, such as the one you mentioned. In the next version, I will add a simple value length checking.

**Comment by PantelisGeorgiadis** [comment]
Hi Will!
In v0.1.28, a guard against invalid implementation versions has been added.

**Comment by PantelisGeorgiadis** [comment]
Hello @will2hew! I'm closing the issue now. If you feel that we can do more on that, please reopen or create a new issue.
